### POST request to get exercises
POST http://localhost:3003/exercise
Content-Type: application/json

{
  "daily_exercises": [1, 0, 2, 0, 3, 0, 2.5],
  "target": 2.5
}
###

### POST request malformed
POST http://localhost:3003/exercise
Content-Type: application/json

{
  "daily_exercises": 1,
  "target": 2.5
}
###
